### PR TITLE
Major changes

### PR DESCRIPTION
**Pull request by rozsa117**
Hash functions refactored, sha1, sha2, md5 hopefully fixed. RC6 and Twofish added to block ciphers.

### CODE REVIEW

**Comment by mitko501** [comment]
I would say we don't need it in dev branch. We no longer use dev branch as pre-branch before merging to master. That's why there are also master changes right now, so it is hard to review your changes. Please create new PR to master and if it is possible, try to somehow clean the code and split it so that each functionality is in one separate commit.

**Comment by ph4r05** [comment]
Agree with @mitko501 that large pull requests are quite a pain to review and merge. It makes it very difficult and messy, error-prone process. Please try to contribute smaller self-contained semantically isolated commits if possible.

Moreover, when doing a PR you should rebase your changes on top of the current master branch so it is up to date in the time of PR (not sure if this PR is rebased to the most up to date master).

Another thing - you should squash redundant commits in the PR, mainly commits like - sha1 added, hopefully fixed. It makes sense to merge "fixed" commit to the "sha1" commit if that fix is related to sha1. Maintainers do not have to review broken sha1 commit and its much cleaner approach. 

I recommend e.g., Source Tree application to do the rebase / squash stuff if you are git-beginner. And just a note - when doing rebase, create another backup branch from the point you are trying to rebase, to be sure. So you will have 2 branches pointed to identical commit. One branch you rebase, the other is just for the backup. If the rebase go wrong you could lose your changes (if you dont have backup branch), so backup helps you to restore it quickly.

**Comment by ph4r05** [comment]
@rozsa117 if you need help with the GIT come over to the office and we can discuss the next steps and the PR fix.

**Comment by ph4r05** [comment]
@rozsa117 please take a look at the current master - some new block ciphers are already round reduced + test vectors: ARIA, CAST, CAMELLIA, IDEA, SEED. Pls do not round reduce them again.

Another thing also for consideration @mitko501 @Bender250 IDEA form this PR is GPL licensed which implies the whole crypto streams must be under GPL. This is maybe too strict for academic purposes which is usually licensed under MIT/BSD.

**Comment by petrs** [comment]
@mitko501 @Bender250 @rozsa117 @ph4r05 Rgarding the license - we would like to to keep project under MIT/BSD. We need to iterate throw other ciphers as well to check the licenses (I opened the issue for this)

**Pull request closed without merging**
