### PR TITLE
Docker file added

### PR DESCRIPTION
**Pull request by ph4r05**
Enables to easily build cryptostreams for Metacentrum (debian9)

### CODE REVIEW

**Comment by Bender250** [comment]
We had this: https://github.com/crocs-muni/eacirc-utils/tree/master/ea_deb_build

The idea was to keep scripts outside of this repository. But if you think it is better suited here, then I can merge it.

**Comment by ph4r05** [comment]
Hmm... I think that if this project should be used by others then it should contain proper build instructions and a Dockerfile. I think that's how other production repositories work. I see this repo as a standalone repository. As a member of CRoCS I didn't know about the Dockerfile, others won't find it either, I think.

Currently, Cryptostreams won't compile on OSX so having proper Dockerfile in the repository would be helpful for an adoption.

**Comment by ph4r05** [comment]
Feel free to merge the dockerfiles so it serves the right purpose. I like having baseimage as an argument so I can build for debian or arbitrary ubuntu versions without changing the docker file.

**Comment by Bender250** [comment]
OK, I am fine with having it in this repository. Should we have it in the root directory? What do you think about utils or tools directory? Do we want to have any other support utilities? If not, then I can accept the PR.

**Comment by ph4r05** [comment]
So lets maybe merge and possibly iterate with improvements?

**Comment by mhajas** [comment]
Hello, thank you for PR. I like the Dockerfile. Maybe I would just add some real-life example of usage into docs. Like for example, what steps do I need to follow to generate an output stream for config file which is stored locally. WDYT?

**Comment by ph4r05** [comment]
> Hello, thank you for PR. I like the Dockerfile. Maybe I would just add some real-life example of usage into docs. Like for example, what steps do I need to follow to generate an output stream for config file which is stored locally. WDYT?

What would you prefer? Working with the container as a tool (i.e., entrypoint = crypto-streams) or working inside the container?

**Comment by mhajas** [comment]
I am not sure. For CryptoStreams developing purposes, I like entrypoint more. However for "common" usage (for example if you have 100 config files), it is probably faster to connect to the container and work inside. @ph4r05 
 and @Bender250 Which one do you like more?

**Comment by ph4r05** [comment]
I've updated the docker file so the CWD is /data which can be mount to a host-based directory so it supports both scenarios. I.e., docker entrypoint & working inside the docker.

I've gave the instructions in the `Docker.md`. If there are not major objections I would suggest to merge and maybe adapt the instructions so it suits you better.

**Comment by Bender250** [comment]
This is perfect, building image builds CryptoStreams, generating data is available trough `docker run`.

I imagine that the checkout repository will differ for devs, but devs will be able to `exec bash` into the container and build the right repository/commit for their needs.

**Comment by ph4r05** [comment]
Thanks! For advanced use-cases I think users can use instructions from Docker.md and get a shell in the container, build own versions of the cryptostreams and so on. Even better they can use the `--mount` to map the cryptostreams project dir directly to the container (I do this quite often).

**Pull request merged**
