### PR TITLE
Sync missing patches from ph4r05/CryptoStreams

### PR DESCRIPTION
**Pull request by mbroz**
Sync from https://github.com/ph4r05/CryptoStreams

### CODE REVIEW

**Comment by ph4r05** [comment]
pls let me know when this PR is ready for review @mbroz

**Comment by mbroz** [comment]
Only link to proper commit to eacirc core submodule is needed to check (IMO current master should work).

**Review by ph4r05 — APPROVED** [review]
LGTM

**Comment by ph4r05** [comment]
@mbroz pls update PR/repo so no travis check is required to merge

**Review by ph4r05 — APPROVED** [review]
LGTM

**Comment by mbroz** [comment]
> @mbroz pls update PR/repo so no travis check is required to merge

Yes, I know, but @petrs must do that, I have no rights for it... (it a rule for protected branch, I guess).

**Pull request merged**
